'use client';
import { useMemo, useState } from 'react';

type Preview={name:string;url:string;file:File};
type Hook={hook:string;angle:string;ctrScore:number;why:string;risk:string};
type Variant={name:string;hook:string;image:string;score?:number;recommendation?:string};
const styles=['BĐS Viral','Luxury','Giá Sốc','Tò Mò','Review Nhà','Đầu Tư'];
const defaults=['3,2 TỶ MÀ CÓ NHÀ NÀY?!','20 PHÚT TỪ TP.HCM?','CĂN NÀY CÓ GÌ ĐẶC BIỆT?'];
const variantDefs=[['PRICE SHOCK','Giá Sốc'],['LOCATION','Vị Trí'],['CURIOSITY','Tò Mò'],['LIFESTYLE','Lifestyle']];

export default function Home(){
 const [person,setPerson]=useState<Preview|null>(null); const [house,setHouse]=useState<Preview|null>(null); const [style,setStyle]=useState('BĐS Viral');
 const [title,setTitle]=useState('Nhà phố 3,2 tỷ gần Bình Chánh – sổ hồng riêng');
 const [propertyInfo,setPropertyInfo]=useState('Giá: 3,2 tỷ\nDiện tích: 4x20m\n3 phòng ngủ, 2 WC\nSổ hồng riêng\nĐường trước nhà 6m\nCách Bình Chánh khoảng 20 phút');
 const [target,setTarget]=useState('Vợ chồng trẻ, gia đình mua nhà ở thực tại TP.HCM và Long An');
 const [hook,setHook]=useState(defaults[0]); const [hooks,setHooks]=useState<Hook[]>([]); const [winner,setWinner]=useState<number|null>(null);
 const [variants,setVariants]=useState<Variant[]>([]); const [best,setBest]=useState<number|null>(null);
 const [hookLoading,setHookLoading]=useState(false); const [variantLoading,setVariantLoading]=useState(false); const [loading,setLoading]=useState(false); const [result,setResult]=useState<string|null>(null);
 const preview=useMemo(()=>house?.url||person?.url||null,[house,person]); const canvasImage=best!==null&&variants[best]?variants[best].image:(variants[0]?.image||preview);
 const pick=(file:File|null,setter:(v:Preview|null)=>void)=>{if(!file||!file.type.startsWith('image/'))return; setter({name:file.name,url:URL.createObjectURL(file),file});};
 const generateHooks=async()=>{setHookLoading(true);setResult(null);try{const r=await fetch('/api/hooks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({propertyInfo,target,style})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Không thể tạo Hook');setHooks(d.hooks||[]);setWinner(typeof d.winner==='number'?d.winner:null);if(typeof d.winner==='number'&&d.hooks?.[d.winner])setHook(d.hooks[d.winner].hook);setResult('AI đã tạo 10 Hook và xếp hạng CTR.');}catch(e){setResult(e instanceof Error?e.message:'Không thể kết nối AI.')}finally{setHookLoading(false)}};
 const makeForm=(variant:string)=>{const fd=new FormData();fd.set('title',title);fd.set('hook',hook);fd.set('style',style);fd.set('variant',variant);fd.set('propertyInfo',propertyInfo);if(person)fd.set('person',person.file,person.file.name);if(house)fd.set('house',house.file,house.file.name);return fd;};
 const generate=async()=>{setLoading(true);setResult(null);setVariants([]);setBest(null);try{if(!person&&!house)throw new Error('Hãy upload ít nhất 1 ảnh MC hoặc căn nhà.');const r=await fetch('/api/generate',{method:'POST',body:makeForm('CURIOSITY')});const d=await r.json();if(!r.ok)throw new Error(d.error||'Có lỗi');setVariants([{name:'Thumbnail',hook,image:d.imageData}]);setBest(0);setResult('Đã tạo thumbnail bằng Nano Banana Pro.');}catch(e){setResult(e instanceof Error?e.message:'Không thể kết nối AI.')}finally{setLoading(false)}};
 const generateVariants=async()=>{setVariantLoading(true);setResult(null);setVariants([]);setBest(null);try{if(!person&&!house)throw new Error('Hãy upload ít nhất 1 ảnh MC hoặc căn nhà.');const out:Variant[]=[];for(const [code,name] of variantDefs){const r=await fetch('/api/generate',{method:'POST',body:makeForm(code)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Lỗi tạo '+name);out.push({name,hook,image:d.imageData});setVariants([...out]);}const judged:Variant[]=[];for(const v of out){const r=await fetch('/api/judge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:v.image,hook:v.hook,propertyInfo})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Lỗi chấm CTR');judged.push({...v,score:Number(j.score)||0,recommendation:j.recommendation});setVariants([...judged]);}const ranked=judged.map((v,i)=>({i,score:v.score||0})).sort((a,b)=>b.score-a.score);setBest(ranked[0]?.i??0);setResult(`Đã tạo ${out.length} biến thể và AI đã chấm CTR.`);}catch(e){setResult(e instanceof Error?e.message:'Không thể tạo biến thể.')}finally{setVariantLoading(false)}};
 const exportImage=()=>{if(!canvasImage)return;const a=document.createElement('a');a.href=canvasImage;a.download='giang-ai-thumbnail.png';a.click();};
 return <main className="app"><header className="topbar"><div className="brand"><div className="logo">G</div><span>Giang AI Thumbnail</span><span className="badge">BETA</span></div><span className="pill">YouTube 1280 × 720</span></header>
 <section className="workspace"><div className="hero"><div><div className="eyebrow">AI CREATIVE STUDIO</div><h1>Nhập thông tin căn nhà. AI lo Hook & Thumbnail.</h1><p>Phân tích sản phẩm, gợi ý Hook có lực hút, tạo nhiều concept và tự chọn phiên bản có điểm CTR cao nhất.</p></div><div className="pill">Hook Director · CTR Judge · Nano Banana Pro · 16:9</div></div>
 <div className="grid"><aside className="card left"><h2>01 · Thông tin sản phẩm</h2>
 <div className="field"><div className="label"><span>Thông tin căn nhà</span><span>{propertyInfo.length} ký tự</span></div><textarea className="textarea large" value={propertyInfo} onChange={e=>setPropertyInfo(e.target.value)} placeholder="Giá, diện tích, pháp lý, vị trí, tiện ích, điểm nổi bật..."/></div>
 <div className="field"><div className="label"><span>Khách hàng mục tiêu</span></div><input className="input" value={target} onChange={e=>setTarget(e.target.value)}/></div>
 <div className="field"><div className="label"><span>Tiêu đề video</span><span>{title.length}/100</span></div><textarea className="textarea" value={title} maxLength={100} onChange={e=>setTitle(e.target.value)}/></div>
 <div className="field"><div className="label"><span>Ảnh MC / Nhân vật</span><span>{person?'✓':''}</span></div><div className="drop"><div className="uploadrow"><div className="preview-sm">{person?<img src={person.url} alt="MC"/>:<span>Upload MC</span>}</div><label className="btn btn-secondary" style={{display:'grid',placeItems:'center',cursor:'pointer'}}>Chọn ảnh<input hidden type="file" accept="image/*" onChange={e=>pick(e.target.files?.[0]||null,setPerson)}/></label></div></div></div>
 <div className="field"><div className="label"><span>Ảnh căn nhà / không gian</span><span>{house?'✓':''}</span></div><div className="drop"><div className="uploadrow"><div className="preview-sm">{house?<img src={house.url} alt="Căn nhà"/>:<span>Upload nhà</span>}</div><label className="btn btn-secondary" style={{display:'grid',placeItems:'center',cursor:'pointer'}}>Chọn ảnh<input hidden type="file" accept="image/*" onChange={e=>pick(e.target.files?.[0]||null,setHouse)}/></label></div></div></div>
 <div className="field"><div className="label"><span>Phong cách</span></div><div className="style-grid">{styles.map(s=><button key={s} className={'style-btn '+(style===s?'active':'')} onClick={()=>setStyle(s)}>{s}</button>)}</div></div>
 <div className="split-buttons"><button className="btn btn-secondary btn-block" onClick={generateHooks} disabled={hookLoading}>{hookLoading?<><span className="spinner"/>Đang tạo Hook...</>:<>⚡ Tạo 10 Hook + CTR</>}</button><button className="btn btn-primary btn-block" onClick={generateVariants} disabled={variantLoading}>{variantLoading?<><span className="spinner"/>Đang tạo 4 bản...</>:<>🔥 Tạo 4 Thumbnail + Judge</>}</button></div>
 <button className="btn btn-secondary btn-block" onClick={generate} disabled={loading}>{loading?<><span className="spinner"/>Đang tạo...</>:<>✨ Tạo 1 Thumbnail nhanh</>}</button>{result&&<div className="footer"><span>{result}</span></div>}</aside>
 <section className="card stage"><div className="stage-toolbar"><div><h2 style={{margin:0,fontSize:15}}>02 · Thumbnail Canvas</h2><span style={{fontSize:11,color:'#73869e'}}>Best variant được ưu tiên</span></div><div className="toolbar-actions"><button className="btn btn-secondary" disabled={!canvasImage} onClick={exportImage}>Export PNG</button></div></div><div className="canvas">{canvasImage?<><img className="bg" src={canvasImage} alt="Thumbnail preview"/><div className="overlay"/><div className="thumb-sub">NHÀ PHỐ · BÌNH CHÁNH</div><div className="thumb-text">{hook}</div></>:<div className="placeholder"><div className="icon">🖼️</div><strong>Upload ảnh để bắt đầu</strong><div>AI sẽ phân tích sản phẩm và tạo concept.</div></div>}</div><div className="score"><div className="score-ring"><div>{best!==null&&variants[best]?.score?variants[best].score:(winner!==null&&hooks[winner]?hooks[winner].ctrScore:92)}</div></div><div><strong>CTR Potential</strong><span>{best!==null?'AI CTR Judge · Best Variant':'Hook strength · Curiosity · Mobile readability'}</span></div></div><div className="footer"><span>AI-safe composition · Không bịa thông tin sản phẩm</span><span>16:9</span></div></section>
 <aside className="card right"><div><h2>03 · Hook Lab</h2><div className="mini">AI phân tích 10 góc Hook và chọn phương án mạnh nhất.</div><div className="field"><input className="input" value={hook} onChange={e=>setHook(e.target.value)} /></div><div className="concepts">{hooks.length>0?hooks.map((h,i)=><button key={`${h.hook}-${i}`} className={'concept '+(winner===i?'winner':'')} onClick={()=>{setHook(h.hook);setWinner(i)}} style={{textAlign:'left',cursor:'pointer'}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><b>{i+1}. {h.angle}</b><strong>{h.ctrScore}</strong></div><p>{h.hook}</p><small>{h.why}{h.risk!=='LOW'?` · Risk ${h.risk}`:''}</small></button>):defaults.map((h,i)=><button key={h} className="concept" onClick={()=>setHook(h)} style={{textAlign:'left',cursor:'pointer'}}><b>{['Curiosity','Price Shock','Distance'][i]}</b><p>{h}</p></button>)}</div></div>
 <div><h2>04 · 4 Thumbnail Variants</h2><div className="concepts">{variants.length?variants.map((v,i)=><button key={`${v.name}-${i}`} className={'concept '+(best===i?'winner':'')} onClick={()=>setBest(i)} style={{textAlign:'left',cursor:'pointer'}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><b>{v.name}</b><strong>{v.score??'—'}</strong></div><p>{v.hook}</p><small>{best===i?'🏆 BEST VARIANT':(v.recommendation||'Chọn để xem')}</small></button>):<div className="concept"><b>Chưa tạo biến thể</b><p>Bấm “Tạo 4 Thumbnail + Judge”.</p></div>}</div></div>
 <div><h2>05 · AI Director</h2><div className="concept"><b>Nguyên tắc thiết kế</b><p>MC và căn nhà là chủ thể thật; AI tối ưu ánh sáng, depth, màu, khoảng trống text và khả năng đọc trên mobile.</p></div></div></aside></div></section></main>
}
