'use client';
import { useMemo, useState } from 'react';

type Preview={name:string;url:string};
const styles=['BĐS Viral','Luxury','Giá Sốc','Tò Mò','Review Nhà','Đầu Tư'];
const defaultHooks=['CĂN NÀY CÓ GÌ ĐẶC BIỆT?','3,2 TỶ CÓ NHÀ NÀY?!','25 PHÚT → TỚI TP.HCM'];

export default function Home(){
 const [person,setPerson]=useState<Preview|null>(null); const [house,setHouse]=useState<Preview|null>(null); const [style,setStyle]=useState('BĐS Viral');
 const [title,setTitle]=useState('Nhà phố 3,2 tỷ gần Bình Chánh – sổ hồng riêng'); const [hook,setHook]=useState(defaultHooks[1]); const [loading,setLoading]=useState(false); const [result,setResult]=useState<string|null>(null); const [generated,setGenerated]=useState<string|null>(null);
 const preview=useMemo(()=>house?.url||person?.url||null,[house,person]);
 const pick=(file:File|null,setter:(v:Preview|null)=>void)=>{if(!file)return; setter({name:file.name,url:URL.createObjectURL(file)});};
 const generate=async()=>{setLoading(true);setResult(null);setGenerated(null);try{if(!person&&!house) throw new Error('Hãy upload ít nhất 1 ảnh MC hoặc căn nhà.'); const fd=new FormData(); fd.set('title',title); fd.set('hook',hook); fd.set('style',style); if(person) fd.set('person',person.url); if(house) fd.set('house',house.url); const r=await fetch('/api/generate',{method:'POST',body:fd}); const d=await r.json(); if(!r.ok) throw new Error(d.error||'Có lỗi'); setGenerated(d.imageData); setResult('Đã tạo concept bằng Gemini.');}catch(e){setResult(e instanceof Error?e.message:'Không thể kết nối AI.')}finally{setLoading(false)}};
 return <main className="app"><header className="topbar"><div className="brand"><div className="logo">G</div><span>Giang AI Thumbnail</span><span className="badge">BETA</span></div><span className="pill">YouTube 1280 × 720</span></header>
 <section className="workspace"><div className="hero"><div><div className="eyebrow">AI CREATIVE STUDIO</div><h1>Biến ảnh thật thành thumbnail có lực hút.</h1><p>Upload MC + căn nhà. AI hiểu chủ thể, bố cục và hook để tạo thumbnail BĐS nổi bật trên màn hình mobile.</p></div><div className="pill">CTR Director · Gemini Vision · 16:9</div></div>
 <div className="grid"><aside className="card left"><h2>01 · Tài nguyên</h2><div className="field"><div className="label"><span>Ảnh MC / Nhân vật</span><span>{person?'✓':''}</span></div><div className="drop"><div className="uploadrow"><div className="preview-sm">{person?<img src={person.url}/>:<span>Kéo ảnh vào đây</span>}</div><label className="btn btn-secondary" style={{display:'grid',placeItems:'center',cursor:'pointer'}}>Chọn ảnh<input hidden type="file" accept="image/*" onChange={e=>pick(e.target.files?.[0]||null,setPerson)}/></label></div></div></div>
 <div className="field"><div className="label"><span>Ảnh căn nhà / không gian</span><span>{house?'✓':''}</span></div><div className="drop"><div className="uploadrow"><div className="preview-sm">{house?<img src={house.url}/>:<span>Upload ảnh nhà</span>}</div><label className="btn btn-secondary" style={{display:'grid',placeItems:'center',cursor:'pointer'}}>Chọn ảnh<input hidden type="file" accept="image/*" onChange={e=>pick(e.target.files?.[0]||null,setHouse)}/></label></div></div></div>
 <div className="field"><div className="label"><span>Tiêu đề video</span><span>{title.length}/100</span></div><textarea className="textarea" value={title} maxLength={100} onChange={e=>setTitle(e.target.value)}/></div>
 <div className="field"><div className="label"><span>Style</span></div><div className="style-grid">{styles.map(s=><button key={s} className={'style-btn '+(style===s?'active':'')} onClick={()=>setStyle(s)}>{s}</button>)}</div></div>
 <button className="btn btn-primary btn-block" onClick={generate} disabled={loading}>{loading?<><span className="spinner"/>Đang phân tích...</>:<>✨ Generate Thumbnail</>}</button>{result&&<div className="footer"><span>{result}</span></div>}</aside>
 <section className="card stage"><div className="stage-toolbar"><div><h2 style={{margin:0,fontSize:15}}>02 · Thumbnail Canvas</h2><span style={{fontSize:11,color:'#73869e'}}>Preview thời gian thực</span></div><div className="toolbar-actions"><button className="btn btn-secondary">Undo</button><button className="btn btn-secondary">Export</button></div></div><div className="canvas">{generated||preview?<><img className="bg" src={generated||preview}/><div className="overlay"/><div className="thumb-sub">NHÀ PHỐ · BÌNH CHÁNH</div><div className="thumb-text">{hook}</div></>:<div className="placeholder"><div className="icon">🖼️</div><strong>Upload ảnh để bắt đầu</strong><div>AI sẽ tự tạo concept, bố cục và hook.</div></div>}</div><div className="score"><div className="score-ring"><div>92</div></div><div><strong>CTR Potential</strong><span>Visual hierarchy · Hook strength · Mobile readability</span></div></div><div className="footer"><span>AI-safe composition · Khuôn mặt & căn nhà được ưu tiên</span><span>16:9</span></div></section>
 <aside className="card right"><div><h2>03 · Hook Lab</h2><div className="mini">AI gợi ý hook ngắn, mạnh, dễ đọc.</div><div className="field"><input className="input" value={hook} onChange={e=>setHook(e.target.value)}/></div><div className="concepts">{defaultHooks.map((h,i)=><button key={h} className="concept" onClick={()=>setHook(h)} style={{textAlign:'left',cursor:'pointer'}}><b>{['Curiosity','Price Shock','Distance'][i]}</b><p>{h}</p></button>)}</div></div><div><h2>04 · AI Director</h2><div className="concept"><b>Đề xuất bố cục</b><p>MC 38% khung hình · căn nhà 62% · text tập trung vùng trái · tương phản cao cho mobile.</p></div></div><button className="btn btn-secondary btn-block">+ Thêm ảnh tham khảo style</button></aside></div></section></main>
}
